org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

## Disable kotlin incremental compilation temporarily to avoid incremental cache races
# You can remove or set to true once builds are stable again
kotlin.incremental=false
